const p = Promise.resolve(new Error("NÃ£o deu certo!"));

console.log('lalalal');


p.then((v) => {
    console.log(v);
}).catch(reason => console.log("Falhou: " + reason));