try {
    const a = 2 + b;
} catch (error) {
    console.log(e);
}

console.log('NAo parrou o codigo!!!')